dataSources = {"web-api-pepper.horizon.tv": 0}

# To check packages on:
# - Love Nature 293
# - Yourtv

# Packages and channel numbers correct as of **18th August 2018**
channels = {"BBC ONE": {"name": "BBC ONE",
                        "sd": {"key": 101, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "30644"}},
                        "hd": {"key": 108, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC TWO": {"name": "BBC TWO",
                        "sd": {"key": 102, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "17154"}},
                        "hd": {"key": 162, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "ITV": {"name": "ITV",
                    "sd": {"key": 103, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "17468"}},
                    "hd": {"key": 113, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "plus1": {"name": "ITV +1",
                              "sd": {"key": 114, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "Channel 4": {"name": "Channel 4",
                          "sd": {"key": 104, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "17155"}},
                          "hd": {"key": 141, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "plus1": {"name": "Channel 4 +1",
                                    "sd": {"key": 142, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "56892"}}}},
            "5": {"name": "5",
                  "sd": {"key": 105, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "17157"}},
                  "hd": {"key": 150, "package": ["Player", "Mix", "Full House", "VIP"]},
                  "plus1": {"name": "5 +1",
                            "sd": {"key": 155, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "BBC FOUR": {"name": "BBC FOUR",
                         "sd": {"key": 107, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "20684"}},
                         "hd": {"key": 163, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Sky1": {"name": "Sky1",
                     "sd": {"key": 110, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "16235"}},
                     "hd": {"key": 109, "package": ["Full House", "VIP"]}},
            "Sky2": {"name": "Sky2",
                     "sd": {"key": 121, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "32151"}}},
            "Sky Witness": {"name": "Sky Witness",
                            "sd": {"key": 112, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17443"}},
                            "hd": {"key": 111, "package": ["Full House", "VIP"]},
                            "plus1": {"name": "Sky Witness +1",
                                      "sd": {"key": 140, "package": ["Mix", "Full House", "VIP"]}}},
            "ITV2": {"name": "ITV2",
                     "sd": {"key": 115, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "20630"}},
                     "hd": {"key": 176, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "ITV2 +1",
                               "sd": {"key": 116, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "ITV3": {"name": "ITV3",
                     "sd": {"key": 117, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "44643"}},
                     "hd": {"key": 177, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "ITV3 +1",
                               "sd": {"key": 174, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "ITV4": {"name": "ITV4",
                     "sd": {"key": 118, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "48020"}},
                     "hd": {"key": 178, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "ITV4 +1",
                               "sd": {"key": 175, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "ITVBe": {"name": "ITVBe",
                      "sd": {"key": 119, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "90257"}},
                      "hd": {"key": 179, "package": ["Full House", "VIP"]},
                      "plus1": {"name": "ITVBe +1",
                                "sd": {"key": 120, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "Sky Arts": {"name": "Sky Arts",
                         "sd": {"key": 122, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "24919"}},
                         "hd": {"key": 206, "package": ["Full House", "VIP"]}},
            "Pick": {"name": "Pick",
                     "sd": {"key": 123, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "W": {"name": "W",
                  "sd": {"key": 125, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "61458"}},
                  "hd": {"key": 191, "package": ["Full House", "VIP"]},
                  "plus1": {"name": "W +1",
                            "sd": {"key": 131, "package": ["Mix", "Full House", "VIP"]}}},
            "Gold": {"name": "Gold",
                     "sd": {"key": 124, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17442"}},
                     "plus1": {"name": "Gold +1",
                               "sd": {"key": 190, "package": ["Mix", "Full House", "VIP"]}}},
            "Dave": {"name": "Dave",
                     "sd": {"key": 127, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "24305"}},
                     "hd": {"key": 194, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "Dave ja vu",
                               "sd": {"key": 211, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "Alibi": {"name": "Alibi",
                      "sd": {"key": 126, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "21258"}},
                      "hd": {"key": 200, "package": ["Full House", "VIP"]},
                      "plus1": {"name": "Alibi +1",
                                "sd": {"key": 130, "package": ["Mix", "Full House", "VIP"]}}},
            "Comedy Central": {"name": "Comedy Central",
                               "sd": {"key": 132, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17420"}},
                               "hd": {"key": 181, "package": ["Full House", "VIP"]},
                               "plus1": {"name": "Comedy Central +1",
                                         "sd": {"key": 133, "package": ["Mix", "Full House", "VIP"]}}},
            "Comedy Central Extra": {"name": "Comedy Central Extra",
                                     "sd": {"key": 182, "package": ["Full House", "VIP"]}},
            "MTV": {"name": "MTV",
                    "sd": {"key": 134, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17447"}},
                    "hd": {"key": 183, "package": ["Full House", "VIP"]}},
            "syfy": {"name": "syfy",
                     "sd": {"key": 135, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17431"}},
                     "hd": {"key": 165, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "syfy +1",
                               "sd": {"key": 136, "package": ["Mix", "Full House", "VIP"]}}},
            "Universal Channel": {"name": "Universal Channel",
                                  "sd": {"key": 137, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "24671"}},
                                  "hd": {"key": 164, "package": ["Full House", "VIP"]},
                                  "plus1": {"name": "Universal Channel +1",
                                            "sd": {"key": 138, "package": ["Mix", "Full House", "VIP"]}}},
            "Challenge": {"name": "Challenge",
                          "sd": {"key": 139, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "plus1": {"name": "Challenge +1",
                                    "sd": {"key": 180, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "E4": {"name": "E4",
                   "sd": {"key": 106, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "25117"}},
                   "hd": {"key": 145, "package": ["Full House", "VIP"]},
                   "plus1": {"name": "E4 +1",
                             "sd": {"key": 146, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "More4": {"name": "More4",
                      "sd": {"key": 147, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "47657"}},
                      "hd": {"key": 195, "package": ["Full House", "VIP"]},
                      "plus1": {"name": "More4 +1",
                                "sd": {"key": 196, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "75805"}}}},
            "CBS Reality": {"name": "CBS Reality",
                            "sd": {"key": 148, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "31756"}},
                            "plus1": {"name": "CBS Reality +1",
                                      "sd": {"key": 201, "package": ["Mix", "Full House", "VIP"]}}},
            "Horror Channel": {"name": "Horror Channel",
                               "sd": {"key": 149, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "42762"}},
                               "plus1": {"name": "Horror Channel +1",
                                         "sd": {"key": 202, "package": ["Mix", "Full House", "VIP"]}}},
            "5*": {"name": "5*",
                   "sd": {"key": 151, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "52336"}},
                   "plus1": {"name": "5* +1",
                             "sd": {"key": 185, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "5 USA": {"name": "5 USA",
                      "sd": {"key": 153, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "52335"}},
                      "plus1": {"name": "5 USA +1",
                                "sd": {"key": 186, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "5 Select": {"name": "5 Select",
                         "sd": {"key": 152, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "5 Spike": {"name": "5 Spike",
                        "sd": {"key": 154, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "100259"}}},
            "Paramount Network": {"name": "Paramount Network",
                                  "sd": {"key": 188, "package": ["Mix", "Full House", "VIP"]},
                                  "hd": {"key": 187, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "109061"}}},
            "E! Entertainment": {"name": "E! Entertainment",
                                 "sd": {"key": 156, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "32195"}}},
            "FOX": {"name": "FOX",
                    "sd": {"key": 157, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "91502"}},
                    "hd": {"key": 199, "package": ["Full House", "VIP"]},
                    "plus1": {"name": "FOX +1",
                              "sd": {"key": 158, "package": ["Mix", "Full House", "VIP"]}}},
            "Made in Leeds": {"name": "Made in Leeds",
                              "sd": {"key": 159, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Real Lives": {"name": "Real Lives",
                           "sd": {"key": 160, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "45005"}},
                           "plus1": {"name": "Real Lives +1",
                                     "sd": {"key": 207, "package": ["Mix", "Full House", "VIP"]}}},
            "BBC ALBA": {"name": "BBC ALBA",
                         "sd": {"key": 161, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "60940"}}},
            "S4C": {"name": "S4C",
                    "sd": {"key": 166, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "25342"}}},
            "TLC": {"name": "TLC",
                    "sd": {"key": 167, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17454"}},
                    "hd": {"key": 168, "package": ["Full House", "VIP"]},
                    "plus1": {"name": "TLC +1",
                              "sd": {"key": 169, "package": ["Mix", "Full House", "VIP"]}}},
            "DMAX": {"name": "DMAX",
                     "sd": {"key": 213, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "58793"}},
                     "plus1": {"name": "DMAX +1",
                               "sd": {"key": 214, "package": ["Mix", "Full House", "VIP"]}}},
            "Quest": {"name": "Quest",
                      "sd": {"key": 172, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "62391"}},
                      "plus1": {"name": "Quest +1",
                                "sd": {"key": 173, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "BET": {"name": "BET",
                    "sd": {"key": 184, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "74023"}}},
            "True Entertainment": {"name": "True Entertainment",
                                   "sd": {"key": 189, "package": ["Mix", "Full House", "VIP"]}},
            "YourTV": {"sd": {"name": "YourTV",
                              "key": 218, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "109164"}}},
            "Drama": {"sd": {"name": "Drama",
                             "key": 128, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "82575"}}},
            "CBS Action": {"name": "CBS Action",
                           "sd": {"key": 192, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "73970"}}},
            "Sony Crime": {"name": "Sony Crime",
                           "sd": {"key": 193, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "74024"}}},
            "4Seven": {"name": "4Seven",
                       "sd": {"key": 143, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "75804"}},
                       "hd": {"key": 203, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "CBS Drama": {"name": "CBS Drama",
                          "sd": {"key": 197, "package": ["Full House", "VIP"], "dataSources": {0: "57827"}}},
            "TruTV": {"name": "TruTV",
                      "sd": {"key": 212, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Sky Cinema Premiere": {"name": "Sky Cinema Premiere",
                                    "sd": {"key": 431, "package": ["VIP", "movies_sky"], "dataSources": {0: "21107"}},
                                    "hd": {"key": 401, "package": ["VIP", "movies_sky_hd"]},
                                    "plus1": {"name": "Sky Cinema Premiere +1",
                                              "sd": {"key": 402, "package": ["VIP", "movies_sky"]}}},
            "Sky Cinema Hits": {"name": "Sky Cinema Hits",
                                "sd": {"key": 433, "package": ["VIP", "movies_sky"], "dataSources": {0: "56141"}},
                                "hd": {"key": 403, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Greats": {"name": "Sky Cinema Greats",
                                  "sd": {"key": 434, "package": ["VIP", "movies_sky"], "dataSources": {0: "24042"}},
                                  "hd": {"key": 404, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Disney": {"name": "Sky Cinema Disney",
                                  "sd": {"key": 435, "package": ["VIP", "movies_sky"], "dataSources": {0: "24034"}},
                                  "hd": {"key": 405, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Family": {"name": "Sky Cinema Family",
                                  "sd": {"key": 436, "package": ["VIP", "movies_sky"], "dataSources": {0: "24040"}},
                                  "hd": {"key": 406, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Action": {"name": "Sky Cinema Action",
                                  "sd": {"key": 437, "package": ["VIP", "movies_sky"], "dataSources": {0: "24031"}},
                                  "hd": {"key": 407, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Comedy": {"name": "Sky Cinema Comedy",
                                  "sd": {"key": 438, "package": ["VIP", "movies_sky"], "dataSources": {0: "24039"}},
                                  "hd": {"key": 408, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Thriller": {"name": "Sky Cinema Thriller",
                                    "sd": {"key": 439, "package": ["VIP", "movies_sky"], "dataSources": {0: "56140"}},
                                    "hd": {"key": 409, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Drama": {"name": "Sky Cinema Drama",
                                 "sd": {"key": 440, "package": ["VIP", "movies_sky"], "dataSources": {0: "24032"}},
                                 "hd": {"key": 410, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Sci Fi & Horror": {"name": "Sky Cinema Sci Fi & Horror",
                                           "sd": {"key": 441, "package": ["VIP", "movies_sky"], "dataSources": {0: "24041"}},
                                           "hd": {"key": 411, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Select": {"name": "Sky Cinema Select",
                                  "sd": {"key": 442, "package": ["VIP", "movies_sky"], "dataSources": {0: "49139"}},
                                  "hd": {"key": 412, "package": ["VIP", "movies_sky_hd"]}},
            "TCM": {"name": "TCM",
                    "sd": {"key": 415, "package": ["Mix", "Full House", "VIP"]},
                    "hd": {"key": 416, "package": ["Full House", "VIP"]},
                    "plus1": {"name": "TCM +1",
                              "sd": {"key": 417, "package": ["Mix", "Full House", "VIP"]}}},
            "Movies 24": {"name": "Movies 24",
                          "sd": {"key": 419, "package": ["Mix", "Full House", "VIP"]},
                          "plus1": {"name": "Movies 24 +1",
                                    "sd": {"key": 420, "package": ["Mix", "Full House", "VIP"]}}},
            "True Movies": {"name": "True Movies",
                            "sd": {"key": 424, "package": ["Full House", "VIP"]}},
            "Sony Movie Channel": {"name": "Sony Movie Channel",
                                   "sd": {"key": 425, "package": ["Mix", "Full House", "VIP"]}},
            "Film4": {"name": "Film4",
                      "sd": {"key": 428, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "21494"}},
                      "hd": {"key": 429, "package": ["Mix", "Full House", "VIP"]},
                      "plus1": {"name": "Film4 +1",
                                "sd": {"key": 430, "package": ["Mix", "Full House", "VIP"]}}},
            "Sky Sports News": {"name": "Sky Sports News",
                                "sd": {"key": 519, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "20643"}},
                                "hd": {"key": 509, "package": ["Full House", "VIP"]}},
            "Sky Sports Mix": {"name": "Sky Sports Mix",
                               "sd": {"key": 520, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "100265"}},
                               "hd": {"key": 510, "package": ["Full House", "VIP"]}},
            "Sky Sports Main Event": {"name": "Sky Sports Main Event",
                                      "sd": {"key": 511, "package": ["VIP"], "dataSources": {0: "17744"}},
                                      "hd": {"key": 501, "package": ["VIP"]}},
            "Sky Sports Premier League": {"name": "Sky Sports Premier League",
                                          "sd": {"key": 512, "package": ["VIP"], "dataSources": {0: "89362"}},
                                          "hd": {"key": 502, "package": ["VIP"]}},
            "Sky Sports Football": {"name": "Sky Sports Football",
                                    "sd": {"key": 513, "package": ["VIP"], "dataSources": {0: "104326"}},
                                    "hd": {"key": 503, "package": ["VIP"]}},
            "Sky Sports Cricket": {"name": "Sky Sports Cricket",
                                   "sd": {"key": 514, "package": ["VIP"], "dataSources": {0: "19036"}},
                                   "hd": {"key": 504, "package": ["VIP"]}},
            "Sky Sports Golf": {"name": "Sky Sports Golf",
                                "sd": {"key": 515, "package": ["VIP"], "dataSources": {0: "24216"}},
                                "hd": {"key": 505, "package": ["VIP"]}},
            "Sky Sports F1": {"name": "Sky Sports F1",
                              "sd": {"key": 516, "package": ["VIP"], "dataSources": {0: "74410"}},
                              "hd": {"key": 506, "package": ["VIP"]}},
            "Sky Sports Action": {"name": "Sky Sports Action",
                                  "sd": {"key": 517, "package": ["VIP"], "dataSources": {0: "19038"}},
                                  "hd": {"key": 507, "package": ["VIP"]}},
            "Sky Sports Arena": {"name": "Sky Sports Arena",
                                 "sd": {"key": 518, "package": ["VIP"], "dataSources": {0: "104323"}},
                                 "hd": {"key": 508, "package": ["VIP"]}},
            "At The Races": {"name": "At The Races",
                             "sd": {"key": 535, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BT Sport 1": {"name": "BT Sport 1",
                           "sd": {"key": 531, "package": ["Full House", "VIP"], "dataSources": {0: "82447"}},
                           "hd": {"key": 527, "package": ["Full House", "VIP"]}},
            "BT Sport 2": {"name": "BT Sport 2",
                           "sd": {"key": 532, "package": ["Full House", "VIP"], "dataSources": {0: "82449"}},
                           "hd": {"key": 528, "package": ["Full House", "VIP"]}},
            "BT Sport 3": {"name": "BT Sport 3",
                           "sd": {"key": 533, "package": ["Full House", "VIP"], "dataSources": {0: "95771"}},
                           "hd": {"key": 529, "package": ["Full House", "VIP"]}},
            "BT Sport ESPN": {"name": "BT Sport ESPN",
                              "sd": {"key": 534, "package": ["Full House", "VIP"], "dataSources": {0: "46594"}},
                              "hd": {"key": 530, "package": ["Full House", "VIP"]}},
            "Eurosport 1": {"name": "Eurosport 1",
                            "sd": {"key": 523, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "18337"}},
                            "hd": {"key": 521, "package": ["Full House", "VIP"]}},
            "Eurosport 2": {"name": "Eurosport 2",
                            "sd": {"key": 524, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "27413"}},
                            "hd": {"key": 522, "package": ["Full House", "VIP"]}},
            "Motorsport TV": {"name": "Motorsport TV",
                              "sd": {"key": 545, "package": ["Mix", "Full House", "VIP"]}},
            "Racing UK": {"name": "Racing UK",
                          "sd": {"key": 536, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "24226"}}},
            "Permier Sports": {"name": "Permier Sports",
                               "sd": {"key": 551, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "79027"}}},
            "Permier Sports 2": {"name": "Permier Sports 2",
                                 "sd": {"key": 552, "package": ["Mix", "Full House", "VIP"]}},
            "Free Sports": {"name": "Free Sports",
                            "sd": {"key": 553, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "105526"}}},
            "Yesterday": {"name": "Yesterday",
                          "sd": {"key": 245, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "31783"}},
                          "plus1": {"name": "Yesterday +1",
                                    "sd": {"key": 246, "package": ["Player", "Mix", "Full House", "VIP"]}}},
            "Eden": {"name": "Eden",
                     "sd": {"key": 247, "package": ["Full House", "VIP"], "dataSources": {0: "35806"}},
                     "hd": {"key": 249, "package": ["Full House", "VIP"]},
                     "plus1": {"name": "Eden +1",
                               "sd": {"key": 248, "package": ["Full House", "VIP"]}}},
            "Discovery Channel": {"name": "Discovery Channel",
                                  "sd": {"key": 250, "package": ["Full House", "VIP"], "dataSources": {0: "17444"}},
                                  "hd": {"key": 251, "package": ["Full House", "VIP"]},
                                  "plus1": {"name": "Discovery Channel +1",
                                            "sd": {"key": 252, "package": ["Full House", "VIP"]}}},
            "Investigation Discovery": {"name": "Investigation Discovery",
                                        "sd": {"key": 170, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "79026"}},
                                        "plus1": {"name": "Investigation Discovery +1",
                                                  "sd": {"key": 171, "package": ["Mix", "Full House", "VIP"]}}},
            "Animal Planet": {"name": "Animal Planet",
                              "sd": {"key": 256, "package": ["Full House", "VIP"], "dataSources": {0: "20707"}},
                              "hd": {"key": 257, "package": ["Full House", "VIP"]},
                              "plus1": {"name": "Animal Planet +1",
                                        "sd": {"key": 258, "package": ["Full House", "VIP"]}}},
            "Discovery Science": {"name": "Discovery Science",
                                  "sd": {"key": 259, "package": ["Full House", "VIP"], "dataSources": {0: "24282"}},
                                  "plus1": {"name": "Discovery Science +1",
                                            "sd": {"key": 260, "package": ["Full House", "VIP"]}}},
            "Discovery Turbo": {"name": "Discovery Turbo",
                                "sd": {"key": 261, "package": ["Full House", "VIP"], "dataSources": {0: "24284"}}},
            "Discovery History": {"name": "Discovery History",
                                  "sd": {"key": 262, "package": ["Full House", "VIP"], "dataSources": {0: "24280"}},
                                  "plus1": {"name": "Discovery History +1",
                                            "sd": {"key": 263, "package": ["Full House", "VIP"]}}},
            "Nat Geo Wild": {"name": "Nat Geo Wild",
                             "sd": {"key": 264, "package": ["Full House", "VIP"], "dataSources": {0: "23305"}},
                             "hd": {"key": 265, "package": ["Full House", "VIP"]}},
            "National Geographic": {"name": "National Geographic",
                                    "sd": {"key": 266, "package": ["Full House", "VIP"], "dataSources": {0: "21592"}},
                                    "hd": {"key": 268, "package": ["Full House", "VIP"]},
                                    "plus1": {"name": "National Geographic +1",
                                              "sd": {"key": 267, "package": ["Full House", "VIP"]}}},
            "Love Nature": {"name": "Love Nature",
                                    "sd": {"key": 294, "package": ["Full House", "VIP"]},
                                    "hd": {"key": 293, "package": ["Full House", "VIP"], "dataSources": {0: "109166"}}},
            "Community Channel": {"name": "Community Channel",
                                  "sd": {"key": 269, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "History": {"name": "History",
                        "sd": {"key": 270, "package": ["Full House", "VIP"], "dataSources": {0: "92402"}},
                        "plus1": {"name": "History +1",
                                  "sd": {"key": 271, "package": ["Full House", "VIP"]}}},
            "H2": {"name": "H2",
                   "sd": {"key": 273, "package": ["Full House", "VIP"], "dataSources": {0: "92403"}},
                   "hd": {"key": 274, "package": ["Full House", "VIP"]}},
            "Lifetime": {"name": "Lifetime",
                         "sd": {"key": 208, "package": ["Full House", "VIP"], "dataSources": {0: "92408"}},
                         "hd": {"key": 209, "package": ["Full House", "VIP"]}},
            "Crime and Investigation": {"name": "Crime and Investigation",
                                        "sd": {"key": 275, "package": ["Full House", "VIP"], "dataSources": {0: "92407"}}},
            "PBS America": {"name": "PBS America",
                            "sd": {"key": 276, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "73510"}}},
            "Forces TV": {"name": "Forces TV",
                          "sd": {"key": 277, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "87987"}}},
            "Good Food": {"name": "Good Food",
                          "sd": {"key": 278, "package": ["Full House", "VIP"], "dataSources": {0: "28634"}},
                          "hd": {"key": 280, "package": ["Full House", "VIP"]},
                          "plus1": {"name": "Good Food +1",
                                    "sd": {"key": 279, "package": ["Full House", "VIP"]}}},
            "Food Network": {"name": "Food Network",
                             "sd": {"key": 291, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "80824"}}},
            "Home": {"name": "Home",
                     "sd": {"key": 281, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "21257"}},
                     "plus1": {"name": "Home +1",
                               "sd": {"key": 282, "package": ["Mix", "Full House", "VIP"]}}},
            "Really": {"name": "Really",
                       "sd": {"key": 129, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "45828"}}},
            "Discovery Home & Health": {"name": "Discovery Home & Health",
                                        "sd": {"key": 284, "package": ["Full House", "VIP"], "dataSources": {0: "24657"}},
                                        "plus1": {"name": "Discovery Home & Health +1",
                                                  "sd": {"key": 285, "package": ["Full House", "VIP"]}}},
            "Discovery Shed": {"name": "Discovery Shed",
                               "sd": {"key": 286, "package": ["Full House", "VIP"], "dataSources": {0: "47455"}}},
            "Ginx Esports TV": {"name": "Ginx Esports TV",
                                "sd": {"key": 290, "package": ["Full House", "VIP"], "dataSources": {0: "81971"}}},
            "Travel Channel": {"name": "Travel Channel",
                               "sd": {"key": 292, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "80827"}}},
            "CBBC": {"name": "CBBC",
                     "sd": {"key": 701, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "29324"}},
                     "hd": {"key": 710, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Cbeebies": {"name": "Cbeebies",
                         "sd": {"key": 702, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "29325"}},
                         "hd": {"key": 711, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Cartoon Network": {"name": "Cartoon Network",
                                "sd": {"key": 704, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "17667"}},
                                "hd": {"key": 732, "package": ["Full House", "VIP"]},
                                "plus1": {"name": "Cartoon Network +1",
                                          "sd": {"key": 705, "package": ["Mix", "Full House", "VIP"]}}},
            "Cartoonito": {"name": "Cartoonito",
                           "sd": {"key": 706, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "31760"}}},
            "Disney XD": {"name": "Disney XD",
                          "sd": {"key": 707, "package": ["Full House", "VIP"], "dataSources": {0: "18379"}},
                          "plus1": {"name": "Disney XD +1",
                                    "sd": {"key": 708, "package": ["Full House", "VIP"]}}},
            "Nickelodeon": {"name": "Nickelodeon",
                            "sd": {"key": 712, "package": ["Full House", "VIP"], "dataSources": {0: "17419"}},
                            "hd": {"key": 714, "package": ["Full House", "VIP"]},
                            "plus1": {"name": "Nickelodeon +1",
                                      "sd": {"key": 713, "package": ["Full House", "VIP"]}}},
            "Nick Junior": {"name": "Nick Junior",
                            "sd": {"key": 715, "package": ["Full House", "VIP"], "dataSources": {0: "24025"}}},
            "Nick Junior Too": {"name": "Nick Junior Too",
                                "sd": {"key": 716, "package": ["Full House", "VIP"]}},
            "Nick Toons": {"name": "Nick Toons",
                           "sd": {"key": 717, "package": ["Full House", "VIP"]}},
            "Disney Channel": {"name": "Disney Channel",
                               "sd": {"key": 724, "package": ["Full House", "VIP"], "dataSources": {0: "18377"}},
                               "plus1": {"name": "Disney Channel +1",
                                         "sd": {"key": 725, "package": ["Full House", "VIP"]}}},
            "Disney Junior": {"name": "Disney Junior",
                              "sd": {"key": 727, "package": ["Full House", "VIP"], "dataSources": {0: "24761"}}},
            "Boomerang": {"name": "Boomerang",
                          "sd": {"key": 730, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "24341"}},
                          "plus1": {"name": "Boomerang +1",
                                    "sd": {"key": 731, "package": ["Mix", "Full House", "VIP"]}}},
            "CITV": {"name": "CITV",
                     "sd": {"key": 734, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "49452"}}},
            "Pop": {"name": "Pop",
                    "sd": {"key": 736, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "100263"}}},
            "Tiny Pop": {"name": "Tiny Pop",
                         "sd": {"key": 737, "package": ["Mix", "Full House", "VIP"]}},
            "MTV Music": {"name": "MTV Music",
                          "sd": {"key": 310, "package": ["Mix", "Full House", "VIP"]}},
            "MTV Live HD": {"name": "MTV Live HD",
                            "hd": {"key": 311, "package": ["Full House", "VIP"]}},
            "MTV Hits": {"name": "MTV Hits",
                         "sd": {"key": 312, "package": ["Full House", "VIP"]}},
            "MTV Base": {"name": "MTV Base",
                         "sd": {"key": 313, "package": ["Full House", "VIP"]}},
            "MTV Dance": {"name": "MTV Dance",
                          "sd": {"key": 314, "package": ["Full House", "VIP"]}},
            "MTV Rocks": {"name": "MTV Rocks",
                          "sd": {"key": 315, "package": ["Full House", "VIP"]}},
            "VH1": {"name": "VH1",
                    "sd": {"key": 316, "package": ["Full House", "VIP"]}},
            "Viva": {"name": "Viva",
                     "sd": {"key": 317, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "4 Music": {"name": "4 Music",
                        "sd": {"key": 337, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "31786"}}},
            "The Box": {"name": "The Box",
                        "sd": {"key": 335, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "21492"}}},
            "Kiss": {"name": "Kiss",
                     "sd": {"key": 338, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "25151"}}},
            "Box Hits": {"name": "Box Hits",
                         "sd": {"key": 336, "package": ["Full House", "VIP"]}},
            "Box Upfront": {"name": "Box Upfront",
                            "sd": {"key": 220, "package": ["Full House", "VIP"]}},
            "Magic": {"name": "Magic",
                      "sd": {"key": 340, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "25607"}}},
            "Kerrang! TV": {"name": "Kerrang! TV",
                            "sd": {"key": 342, "package": ["Full House", "VIP"]}},
            "Vintage TV": {"name": "Vintage TV",
                           "sd": {"key": 343, "package": ["Mix", "Full House", "VIP"]}},
            "Clubland": {"name": "Clubland",
                         "sd": {"key": 345, "package": ["Mix", "Full House", "VIP"]}},
            "BBC News": {"name": "BBC News",
                         "sd": {"key": 601, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "19037"}},
                         "hd": {"key": 604, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Sky News": {"name": "Sky News",
                         "sd": {"key": 602, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "16234"}},
                         "hd": {"key": 603, "package": ["Full House", "VIP"]}},
            "BBC Parliament": {"name": "BBC Parliament",
                               "sd": {"key": 605, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "20685"}}},
            "CNN": {"name": "CNN",
                    "sd": {"key": 607, "package": ["Player", "Mix", "Full House", "VIP"], "dataSources": {0: "68053"}}},
            "Bloomberg": {"name": "Bloomberg",
                          "sd": {"key": 609, "package": ["Mix", "Full House", "VIP"]}},
            "CNBC": {"name": "CNBC",
                     "sd": {"key": 613, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Euronews": {"name": "Euronews",
                         "sd": {"key": 620, "package": ["Mix", "Full House", "VIP"]}},
            "NDTV 24x7": {"name": "NDTV 24x7",
                          "sd": {"key": 621, "package": ["Mix", "Full House", "VIP"], "dataSources": {0: "74025"}}},
            "BBC Radio 1": {"name": "BBC Radio 1",
                            "sd": {"key": 901, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 1 Xtra": {"name": "BBC Radio 1 Xtra",
                                 "sd": {"key": 907, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 2": {"name": "BBC Radio 2",
                            "sd": {"key": 902, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 3": {"name": "BBC Radio 3",
                            "sd": {"key": 903, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 4 FM": {"name": "BBC Radio 4 FM",
                               "sd": {"key": 904, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 4 Extra": {"name": "BBC Radio 4 Extra",
                                  "sd": {"key": 910, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 4 Long Wave": {"name": "BBC Radio 4 Long Wave",
                                      "sd": {"key": 911, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 5 Live": {"name": "BBC Radio 5 Live",
                                 "sd": {"key": 905, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 5 Live Sports Extra": {"name": "BBC Radio 5 Live Sports Extra",
                                              "sd": {"key": 908, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC Radio 6 Music": {"name": "BBC Radio 6 Music",
                                  "sd": {"key": 909, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC World Service": {"name": "BBC World Service",
                                  "sd": {"key": 906, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Absolute Radio": {"name": "Absolute Radio",
                               "sd": {"key": 915, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Smooth Radio": {"name": "Smooth Radio",
                             "sd": {"key": 916, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Heart FM": {"name": "Heart FM",
                         "sd": {"key": 918, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "LBC": {"name": "LBC",
                    "sd": {"key": 919, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Classic FM": {"name": "Classic FM",
                           "sd": {"key": 922, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Gold Radio": {"name": "Gold Radio",
                           "sd": {"key": 923, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Planet Rock": {"name": "Planet Rock",
                            "sd": {"key": 924, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Magic Radio": {"name": "Magic Radio",
                            "sd": {"key": 928, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Absolute 80s": {"name": "Absolute 80s",
                             "sd": {"key": 951, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Absolute Classic Rock": {"name": "Absolute Classic Rock",
                                      "sd": {"key": 952, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Capital FM": {"name": "Capital FM",
                           "sd": {"key": 958, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Capital Xtra": {"name": "Capital Xtra",
                             "sd": {"key": 959, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Radio X": {"name": "Radio X",
                        "sd": {"key": 960, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Kiss FM": {"name": "Kiss FM",
                        "sd": {"key": 963, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "talkSPORT": {"name": "talkSPORT",
                          "sd": {"key": 927, "package": ["Player", "Mix", "Full House", "VIP"]}}
        }
