dataSources = {"web-api-pepper.horizon.tv": 0}

# Packages and channel numbers correct as of **19th August 2018**
# Data from 'http://www.virginmedia.com/content/dam/virginmedia/dotcom/documents/Redwood/ChannelGuide_Aug2018_06.pdf'

channels = {"bbc_one": {"name": "BBC ONE",
                        "sd": {"key": 101, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "30644"}},
                        "hd": {"key": 108, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_two": {"name": "BBC TWO",
                        "sd": {"key": 102, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "17154"}},
                        "hd": {"key": 162, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "itv": {"name": "ITV",
                    "sd": {"key": 103, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "17468"}},
                    "hd": {"key": 113, "package": ["Player", "Mix", "Fun", "Full House"]},
                    "plus1": {"name": "ITV +1",
                              "sd": {"key": 114, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "channel_4": {"name": "Channel 4",
                          "sd": {"key": 104, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "17155"}},
                          "hd": {"key": 141, "package": ["Player", "Mix", "Fun", "Full House"]},
                          "plus1": {"name": "Channel 4 +1",
                                    "sd": {"key": 142, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "56892"}}}},
            "five": {"name": "5",
                     "sd": {"key": 105, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "17157"}},
                     "hd": {"key": 150, "package": ["Player", "Mix", "Fun", "Full House"]},
                     "plus1": {"name": "5 +1",
                               "sd": {"key": 155, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "bbc_four": {"name": "BBC FOUR",
                         "sd": {"key": 107, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "20684"}},
                         "hd": {"key": 163, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "sky1": {"name": "Sky1",
                     "sd": {"key": 110, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "16235"}},
                     "hd": {"key": 109, "package": ["Full House"]}},
            "sky2": {"name": "Sky2",
                     "sd": {"key": 121, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "32151"}}},
            "sky_witness": {"name": "Sky Witness",
                            "sd": {"key": 112, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17443"}},
                            "hd": {"key": 111, "package": ["Full House"]},
                            "plus1": {"name": "Sky Witness +1",
                                      "sd": {"key": 140, "package": ["Mix", "Fun", "Full House"]}}},
            "itv2": {"name": "ITV2",
                     "sd": {"key": 115, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "20630"}},
                     "hd": {"key": 176, "package": ["Full House"]},
                     "plus1": {"name": "ITV2 +1",
                               "sd": {"key": 116, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "itv3": {"name": "ITV3",
                     "sd": {"key": 117, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "44643"}},
                     "hd": {"key": 177, "package": ["Full House"]},
                     "plus1": {"name": "ITV3 +1",
                               "sd": {"key": 174, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "itv4": {"name": "ITV4",
                     "sd": {"key": 118, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "48020"}},
                     "hd": {"key": 178, "package": ["Full House"]},
                     "plus1": {"name": "ITV4 +1",
                               "sd": {"key": 175, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "itvbe": {"name": "ITVBe",
                      "sd": {"key": 119, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "90257"}},
                      "hd": {"key": 179, "package": ["Full House"]},
                      "plus1": {"name": "ITVBe +1",
                                "sd": {"key": 120, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "sky_arts": {"name": "Sky Arts",
                         "sd": {"key": 122, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "24919"}},
                         "hd": {"key": 206, "package": ["Full House"]}},
            "pick": {"name": "Pick",
                     "sd": {"key": 123, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "w": {"name": "W",
                  "sd": {"key": 125, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "61458"}},
                  "hd": {"key": 191, "package": ["Full House"]},
                  "plus1": {"name": "W +1",
                            "sd": {"key": 131, "package": ["Mix", "Fun", "Full House"]}}},
            "gold": {"name": "Gold",
                     "sd": {"key": 124, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17442"}},
                     "plus1": {"name": "Gold +1",
                               "sd": {"key": 190, "package": ["Mix", "Fun", "Full House"]}}},
            "dave": {"name": "Dave",
                     "sd": {"key": 127, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "24305"}},
                     "hd": {"key": 194, "package": ["Mix", "Fun", "Full House"]},
                     "plus1": {"name": "Dave ja vu",
                               "sd": {"key": 211, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "alibi": {"name": "Alibi",
                      "sd": {"key": 126, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "21258"}},
                      "hd": {"key": 200, "package": ["Full House"]},
                      "plus1": {"name": "Alibi +1",
                                "sd": {"key": 130, "package": ["Mix", "Fun", "Full House"]}}},
            "comedy_central": {"name": "Comedy Central",
                               "sd": {"key": 132, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17420"}},
                               "hd": {"key": 181, "package": ["Full House"]},
                               "plus1": {"name": "Comedy Central +1",
                                         "sd": {"key": 133, "package": ["Mix", "Fun", "Full House"]}}},
            "comedy_central_extra": {"name": "Comedy Central Extra",
                                     "sd": {"key": 182, "package": ["Fun", "Full House"]}},
            "mtv": {"name": "MTV",
                    "sd": {"key": 134, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17447"}},
                    "hd": {"key": 183, "package": ["Full House"]}},
            "syfy": {"name": "syfy",
                     "sd": {"key": 135, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17431"}},
                     "hd": {"key": 165, "package": ["Full House"]},
                     "plus1": {"name": "syfy +1",
                               "sd": {"key": 136, "package": ["Mix", "Fun", "Full House"]}}},
            "universal_channel": {"name": "Universal Channel",
                                  "sd": {"key": 137, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "24671"}},
                                  "hd": {"key": 164, "package": ["Full House"]},
                                  "plus1": {"name": "Universal Channel +1",
                                            "sd": {"key": 138, "package": ["Mix", "Fun", "Full House"]}}},
            "challenge": {"name": "Challenge",
                          "sd": {"key": 139, "package": ["Player", "Mix", "Fun", "Full House"]},
                          "plus1": {"name": "Challenge +1",
                                    "sd": {"key": 180, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "e4": {"name": "E4",
                   "sd": {"key": 106, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "25117"}},
                   "hd": {"key": 145, "package": ["Full House"]},
                   "plus1": {"name": "E4 +1",
                             "sd": {"key": 146, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "more4": {"name": "More4",
                      "sd": {"key": 147, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "47657"}},
                      "hd": {"key": 195, "package": ["Full House"]},
                      "plus1": {"name": "More4 +1",
                                "sd": {"key": 196, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "75805"}}}},
            "cbs_reality": {"name": "CBS Reality",
                            "sd": {"key": 148, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "31756"}},
                            "plus1": {"name": "CBS Reality +1",
                                      "sd": {"key": 201, "package": ["Mix", "Fun", "Full House"]}}},
            "horror": {"name": "Horror Channel",
                       "sd": {"key": 149, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "42762"}},
                       "plus1": {"name": "Horror Channel +1",
                                 "sd": {"key": 202, "package": ["Mix", "Fun", "Full House"]}}},
            "5*": {"name": "5*",
                   "sd": {"key": 151, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "52336"}},
                   "plus1": {"name": "5* +1",
                             "sd": {"key": 185, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "5select": {"name": "5 Select",
                        "sd": {"key": 152, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "5usa": {"name": "5 USA",
                     "sd": {"key": 153, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "52335"}},
                     "plus1": {"name": "5 USA +1",
                               "sd": {"key": 186, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "5spike": {"name": "5 Spike",
                       "sd": {"key": 154, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "100259"}}},
            "paramount_network": {"name": "Paramount Network",
                                  "sd": {"key": 188, "package": ["Player", "Mix", "Fun", "Full House"]},
                                  "hd": {"key": 187, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "109061"}}},
            "e!": {"name": "E! Entertainment",
                   "sd": {"key": 156, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "32195"}}},
            "fox": {"name": "FOX",
                    "sd": {"key": 157, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "91502"}},
                    "hd": {"key": 199, "package": ["Full House"]},
                    "plus1": {"name": "FOX +1",
                              "sd": {"key": 158, "package": ["Mix", "Fun", "Full House"]}}},
            "made_in_leeds": {"name": "Made in Leeds",
                              "sd": {"key": 159, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "real_lives": {"name": "Real Lives",
                           "sd": {"key": 160, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "45005"}},
                           "plus1": {"name": "Real Lives +1",
                                     "sd": {"key": 207, "package": ["Mix", "Fun", "Full House"]}}},
            "bbc_alba": {"name": "BBC ALBA",
                         "sd": {"key": 161, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "60940"}}},
            "s4c": {"name": "S4C",
                    "sd": {"key": 166, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "25342"}}},
            "tlc": {"name": "TLC",
                    "sd": {"key": 167, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17454"}},
                    "hd": {"key": 168, "package": ["Full House"]},
                    "plus1": {"name": "TLC +1",
                              "sd": {"key": 169, "package": ["Mix", "Fun", "Full House"]}}},
            "dmax": {"name": "DMAX",
                     "sd": {"key": 213, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "58793"}},
                     "plus1": {"name": "DMAX +1",
                               "sd": {"key": 214, "package": ["Mix", "Fun", "Full House"]}}},
            "quest": {"name": "Quest",
                      "sd": {"key": 172, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "62391"}},
                      "plus1": {"name": "Quest +1",
                                "sd": {"key": 173, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "bet": {"name": "BET",
                    "sd": {"key": 184, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "74023"}}},
            "true_entertainment": {"name": "True Entertainment",
                                   "sd": {"key": 189, "package": ["Player", "Mix", "Fun", "Full House"]},
                                   "plus1": {"name": "True Entertainment",
                                             "sd": {"key": 220, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "yourtV": {"sd": {"name": "YourTV",
                              "key": 218, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "109164"}}},
            "drama": {"sd": {"name": "Drama",
                             "key": 128, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "82575"}}},
            "cbs_action": {"name": "CBS Action",
                           "sd": {"key": 192, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "73970"}}},
            "sony_crime": {"name": "Sony Crime",
                           "sd": {"key": 193, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "74024"}}},
            "4seven": {"name": "4Seven",
                       "sd": {"key": 143, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "75804"}},
                       "hd": {"key": 203, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "cbs_drama": {"name": "CBS Drama",
                          "sd": {"key": 197, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "57827"}}},
            "tru_tv": {"name": "TruTV",
                       "sd": {"key": 212, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "sky_cinema_premiere": {"name": "Sky Cinema Premiere",
                                    "sd": {"key": 431, "package": ["movies_sky"], "dataSources": {0: "21107"}},
                                    "hd": {"key": 401, "package": ["movies_sky_hd"]},
                                    "plus1": {"name": "Sky Cinema Premiere +1",
                                              "sd": {"key": 402, "package": ["movies_sky"]}}},
            "sky_cinema_hits": {"name": "Sky Cinema Hits",
                                "sd": {"key": 433, "package": ["movies_sky"], "dataSources": {0: "56141"}},
                                "hd": {"key": 403, "package": ["movies_sky_hd"]}},
            "sky_cinema_greats": {"name": "Sky Cinema Greats",
                                  "sd": {"key": 434, "package": ["movies_sky"], "dataSources": {0: "24042"}},
                                  "hd": {"key": 404, "package": ["movies_sky_hd"]}},
            "sky_cinema_disney": {"name": "Sky Cinema Disney",
                                  "sd": {"key": 435, "package": ["movies_sky"], "dataSources": {0: "24034"}},
                                  "hd": {"key": 405, "package": ["movies_sky_hd"]}},
            "sky_cinema_family": {"name": "Sky Cinema Family",
                                  "sd": {"key": 436, "package": ["movies_sky"], "dataSources": {0: "24040"}},
                                  "hd": {"key": 406, "package": ["movies_sky_hd"]}},
            "sky_cinema_action": {"name": "Sky Cinema Action",
                                  "sd": {"key": 437, "package": ["movies_sky"], "dataSources": {0: "24031"}},
                                  "hd": {"key": 407, "package": ["movies_sky_hd"]}},
            "sky_cinema_comedy": {"name": "Sky Cinema Comedy",
                                  "sd": {"key": 438, "package": ["movies_sky"], "dataSources": {0: "24039"}},
                                  "hd": {"key": 408, "package": ["movies_sky_hd"]}},
            "sky_cinema_thriller": {"name": "Sky Cinema Thriller",
                                    "sd": {"key": 439, "package": ["movies_sky"], "dataSources": {0: "56140"}},
                                    "hd": {"key": 409, "package": ["movies_sky_hd"]}},
            "sky_cinema_drama": {"name": "Sky Cinema Drama",
                                 "sd": {"key": 440, "package": ["movies_sky"], "dataSources": {0: "24032"}},
                                 "hd": {"key": 410, "package": ["movies_sky_hd"]}},
            "sky_cinema_sci_fi_": {"name": "Sky Cinema Sci Fi & Horror",
                                           "sd": {"key": 441, "package": ["movies_sky"], "dataSources": {0: "24041"}},
                                           "hd": {"key": 411, "package": ["movies_sky_hd"]}},
            "sky_cinema_select": {"name": "Sky Cinema Select",
                                  "sd": {"key": 442, "package": ["movies_sky"], "dataSources": {0: "49139"}},
                                  "hd": {"key": 412, "package": ["movies_sky_hd"]}},
            "tcm": {"name": "TCM",
                    "sd": {"key": 415, "package": ["Mix", "Fun", "Full House"]},
                    "hd": {"key": 416, "package": ["Full House"]},
                    "plus1": {"name": "TCM +1",
                              "sd": {"key": 417, "package": ["Mix", "Fun", "Full House"]}}},
            "movies24": {"name": "Movies 24",
                         "sd": {"key": 419, "package": ["Mix", "Fun", "Full House"]},
                         "plus1": {"name": "Movies 24 +1",
                                   "sd": {"key": 420, "package": ["Mix", "Fun", "Full House"]}}},
            "true_movies": {"name": "True Movies",
                            "sd": {"key": 424, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "sony_movie_channel": {"name": "Sony Movie Channel",
                                   "sd": {"key": 425, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "movies4men": {"name": "Movies4Men",
                                   "sd": {"key": 426, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "film4": {"name": "Film4",
                      "sd": {"key": 428, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "21494"}},
                      "hd": {"key": 429, "package": ["Mix", "Fun", "Full House"]},
                      "plus1": {"name": "Film4 +1",
                                "sd": {"key": 430, "package": ["Mix", "Fun", "Full House"]}}},
            "sky_sports_news": {"name": "Sky Sports News",
                                "sd": {"key": 519, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "20643"}},
                                "hd": {"key": 509, "package": ["Full House"]}},
            "sky_sports_mix": {"name": "Sky Sports Mix",
                               "sd": {"key": 520, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "100265"}},
                               "hd": {"key": 510, "package": ["Full House"]}},
            "sky_sports_main_event": {"name": "Sky Sports Main Event",
                                      "sd": {"key": 511, "package": ["sports_sky"], "dataSources": {0: "17744"}},
                                      "hd": {"key": 501, "package": ["sports_sky_hd"]}},
            "sky_sports_premier_league": {"name": "Sky Sports Premier League",
                                          "sd": {"key": 512, "package": ["sports_sky"], "dataSources": {0: "89362"}},
                                          "hd": {"key": 502, "package": ["sports_sky_hd"]}},
            "sky_sports_football": {"name": "Sky Sports Football",
                                    "sd": {"key": 513, "package": ["sports_sky"], "dataSources": {0: "104326"}},
                                    "hd": {"key": 503, "package": ["sports_sky_hd"]}},
            "sky_sports_cricket": {"name": "Sky Sports Cricket",
                                   "sd": {"key": 514, "package": ["sports_sky"], "dataSources": {0: "19036"}},
                                   "hd": {"key": 504, "package": ["sports_sky_hd"]}},
            "sky_sports_golf": {"name": "Sky Sports Golf",
                                "sd": {"key": 515, "package": ["sports_sky"], "dataSources": {0: "24216"}},
                                "hd": {"key": 505, "package": ["sports_sky_hd"]}},
            "sky_sports_f1": {"name": "Sky Sports F1",
                              "sd": {"key": 516, "package": ["sports_sky"], "dataSources": {0: "74410"}},
                              "hd": {"key": 506, "package": ["sports_sky_hd"]}},
            "sky_sports_action": {"name": "Sky Sports Action",
                                  "sd": {"key": 517, "package": ["sports_sky"], "dataSources": {0: "19038"}},
                                  "hd": {"key": 507, "package": ["sports_sky_hd"]}},
            "sky_sports_arena": {"name": "Sky Sports Arena",
                                 "sd": {"key": 518, "package": ["sports_sky"], "dataSources": {0: "104323"}},
                                 "hd": {"key": 508, "package": ["sports_sky_hd"]}},
            "at_the_races": {"name": "At The Races",
                             "sd": {"key": 535, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bt_sport_1": {"name": "BT Sport 1",
                           "sd": {"key": 531, "package": ["Full House"], "dataSources": {0: "82447"}},
                           "hd": {"key": 527, "package": ["Full House"]}},
            "bt_sport_2": {"name": "BT Sport 2",
                           "sd": {"key": 532, "package": ["Full House"], "dataSources": {0: "82449"}},
                           "hd": {"key": 528, "package": ["Full House"]}},
            "bt_sport_3": {"name": "BT Sport 3",
                           "sd": {"key": 533, "package": ["Full House"], "dataSources": {0: "95771"}},
                           "hd": {"key": 529, "package": ["Full House"]}},
            "bt_sport_espn": {"name": "BT Sport ESPN",
                              "sd": {"key": 534, "package": ["Full House"], "dataSources": {0: "46594"}},
                              "hd": {"key": 530, "package": ["Full House"]}},
            "eurosport1": {"name": "Eurosport 1",
                           "sd": {"key": 523, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "18337"}},
                           "hd": {"key": 521, "package": ["Full House"]}},
            "eurosport2": {"name": "Eurosport 2",
                           "sd": {"key": 524, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "27413"}},
                           "hd": {"key": 522, "package": ["Full House"]}},
            "motorsport_tv": {"name": "Motorsport TV",
                              "sd": {"key": 545, "package": ["Mix", "Fun", "Full House"]}},
            "permier_sports": {"name": "Permier Sports",
                               "sd": {"key": 551, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "79027"}}},
            "permier_sports2": {"name": "Permier Sports 2",
                                "sd": {"key": 552, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "free_sports": {"name": "Free Sports",
                            "sd": {"key": 553, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "105526"}}},
            "yesterday": {"name": "Yesterday",
                          "sd": {"key": 245, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "31783"}},
                          "plus1": {"name": "Yesterday +1",
                                    "sd": {"key": 246, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "eden": {"name": "Eden",
                     "sd": {"key": 247, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "35806"}},
                     "hd": {"key": 249, "package": ["Full House"]},
                     "plus1": {"name": "Eden +1",
                               "sd": {"key": 248, "package": ["Mix", "Fun", "Full House"]}}},
            "discovery_channel": {"name": "Discovery Channel",
                                  "sd": {"key": 250, "package": ["Fun", "Full House"], "dataSources": {0: "17444"}},
                                  "hd": {"key": 251, "package": ["Full House"]},
                                  "plus1": {"name": "Discovery Channel +1",
                                            "sd": {"key": 252, "package": ["Fun", "Full House"]}}},
            "investigation_discovery": {"name": "Investigation Discovery",
                                        "sd": {"key": 170, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "79026"}},
                                        "plus1": {"name": "Investigation Discovery +1",
                                                  "sd": {"key": 171, "package": ["Mix", "Fun", "Full House"]}}},
            "animal_planet": {"name": "Animal Planet",
                              "sd": {"key": 256, "package": ["Fun", "Full House"], "dataSources": {0: "20707"}},
                              "hd": {"key": 257, "package": ["Full House"]},
                              "plus1": {"name": "Animal Planet +1",
                                        "sd": {"key": 258, "package": ["Fun", "Full House"]}}},
            "discovery_science": {"name": "Discovery Science",
                                  "sd": {"key": 259, "package": ["Fun", "Full House"], "dataSources": {0: "24282"}},
                                  "plus1": {"name": "Discovery Science +1",
                                            "sd": {"key": 260, "package": ["Fun", "Full House"]}}},
            "discovery_turbo": {"name": "Discovery Turbo",
                                "sd": {"key": 261, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "24284"}}},
            "discovery_history": {"name": "Discovery History",
                                  "sd": {"key": 262, "package": ["Fun", "Full House"], "dataSources": {0: "24280"}},
                                  "plus1": {"name": "Discovery History +1",
                                            "sd": {"key": 263, "package": ["Fun", "Full House"]}}},
            "nat_geo_wild": {"name": "Nat Geo Wild",
                             "sd": {"key": 264, "package": ["Full House"], "dataSources": {0: "23305"}},
                             "hd": {"key": 265, "package": ["Full House"]}},
            "national_geographic": {"name": "National Geographic",
                                    "sd": {"key": 266, "package": ["Fun", "Full House"], "dataSources": {0: "21592"}},
                                    "hd": {"key": 268, "package": ["Full House"]},
                                    "plus1": {"name": "National Geographic +1",
                                              "sd": {"key": 267, "package": ["Full House"]}}},
            "love_nature": {"name": "Love Nature",
                                    "sd": {"key": 294, "package": ["Mix", "Fun", "Full House"]},
                                    "hd": {"key": 293, "package": ["Full House"], "dataSources": {0: "109166"}}},
            "horse_and_country": {"name": "Horse & Country",
                                  "sd": {"key": 298, "package": ["Mix", "Fun", "Full House"]}},
            "together": {"name": "Together",
                         "sd": {"key": 269, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "history": {"name": "History",
                        "sd": {"key": 270, "package": ["Full House"], "dataSources": {0: "92402"}},
                        "plus1": {"name": "History +1",
                                  "sd": {"key": 271, "package": ["Full House"]}}},
            "h2": {"name": "H2",
                   "sd": {"key": 273, "package": ["Fun", "Full House"], "dataSources": {0: "92403"}},
                   "hd": {"key": 274, "package": ["Full House"]}},
            "lifetime": {"name": "Lifetime",
                         "sd": {"key": 208, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "92408"}},
                         "hd": {"key": 209, "package": ["Full House"]},
                         "plus1": {"name": "Lifetime +1",
                                   "sd": {"key": 225, "package": ["Mix", "Fun", "Full House"]}}},
            "crime_and_investigation": {"name": "Crime and Investigation",
                                        "sd": {"key": 275, "package": ["Full House"], "dataSources": {0: "92407"}},
                                        "plus1": {"name": "Crime and Investigation +1",
                                                  "sd": {"key": 224, "package": ["Full House"]}}},
            "pbs_america": {"name": "PBS America",
                            "sd": {"key": 276, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "73510"}}},
            "forces_tv": {"name": "Forces TV",
                          "sd": {"key": 277, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "87987"}}},
            "good_food": {"name": "Good Food",
                          "sd": {"key": 278, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "28634"}},
                          "hd": {"key": 280, "package": ["Full House"]},
                          "plus1": {"name": "Good Food +1",
                                    "sd": {"key": 279, "package": ["Mix", "Fun", "Full House"]}}},
            "food_network": {"name": "Food Network",
                             "sd": {"key": 291, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "80824"}}},
            "home": {"name": "Home",
                     "sd": {"key": 281, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "21257"}},
                     "plus1": {"name": "Home +1",
                               "sd": {"key": 282, "package": ["Player", "Mix", "Fun", "Full House"]}}},
            "really": {"name": "Really",
                       "sd": {"key": 129, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "45828"}}},
            "discovery_home_and_health": {"name": "Discovery Home & Health",
                                          "sd": {"key": 284, "package": ["Full House"], "dataSources": {0: "24657"}},
                                          "plus1": {"name": "Discovery Home & Health +1",
                                                    "sd": {"key": 285, "package": ["Full House"]}}},
            "discovery_shed": {"name": "Discovery Shed",
                               "sd": {"key": 286, "package": ["Full House"], "dataSources": {0: "47455"}}},
            "ginx": {"name": "Ginx Esports TV",
                     "sd": {"key": 290, "package": ["Full House"], "dataSources": {0: "81971"}}},
            "travel_channel": {"name": "Travel Channel",
                               "sd": {"key": 292, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "80827"}}},
            "cbbc": {"name": "CBBC",
                     "sd": {"key": 701, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "29324"}},
                     "hd": {"key": 710, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "cbeebies": {"name": "Cbeebies",
                         "sd": {"key": 702, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "29325"}},
                         "hd": {"key": 711, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "cartoon_network": {"name": "Cartoon Network",
                                "sd": {"key": 704, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "17667"}},
                                "hd": {"key": 732, "package": ["Full House"]},
                                "plus1": {"name": "Cartoon Network +1",
                                          "sd": {"key": 705, "package": ["Mix", "Fun", "Full House"]}}},
            "cartoonito": {"name": "Cartoonito",
                           "sd": {"key": 706, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "31760"}}},
            "disney_xd": {"name": "Disney XD",
                          "sd": {"key": 707, "package": ["Full House"], "dataSources": {0: "18379"}},
                          "plus1": {"name": "Disney XD +1",
                                    "sd": {"key": 708, "package": ["Full House"]}}},
            "nickelodeon": {"name": "Nickelodeon",
                            "sd": {"key": 712, "package": ["Fun", "Full House"], "dataSources": {0: "17419"}},
                            "hd": {"key": 714, "package": ["Full House"]},
                            "plus1": {"name": "Nickelodeon +1",
                                      "sd": {"key": 713, "package": ["Fun", "Full House"]}}},
            "nick_junior": {"name": "Nick Junior",
                            "sd": {"key": 715, "package": ["Fun", "Full House"], "dataSources": {0: "24025"}}},
            "nick_junior_too": {"name": "Nick Junior Too",
                                "sd": {"key": 716, "package": ["Full House"]}},
            "nick_toons": {"name": "Nicktoons",
                           "sd": {"key": 717, "package": ["Fun", "Full House"]}},
            "disney_channel": {"name": "Disney Channel",
                               "sd": {"key": 724, "package": ["Full House"], "dataSources": {0: "18377"}},
                               "plus1": {"name": "Disney Channel +1",
                                         "sd": {"key": 725, "package": ["Full House"]}}},
            "disney_junior": {"name": "Disney Junior",
                              "sd": {"key": 727, "package": ["Full House"], "dataSources": {0: "24761"}}},
            "boomerang": {"name": "Boomerang",
                          "sd": {"key": 730, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "24341"}},
                          "plus1": {"name": "Boomerang +1",
                                    "sd": {"key": 731, "package": ["Mix", "Fun", "Full House"]}}},
            "citv": {"name": "CITV",
                     "sd": {"key": 734, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "49452"}}},
            "pop": {"name": "Pop",
                    "sd": {"key": 736, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "100263"}}},
            "tiny_pop": {"name": "Tiny Pop",
                         "sd": {"key": 737, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "mtv_music": {"name": "MTV Music",
                          "sd": {"key": 310, "package": ["Mix", "Fun", "Full House"]}},
            "mtv_live_hd": {"name": "MTV Live HD",
                            "hd": {"key": 311, "package": ["Full House"]}},
            "mtv_hits": {"name": "MTV Hits",
                         "sd": {"key": 312, "package": ["Fun", "Full House"]}},
            "mtv_base": {"name": "MTV Base",
                         "sd": {"key": 313, "package": ["Fun", "Full House"]}},
            "mtv_dance": {"name": "MTV Dance",
                          "sd": {"key": 314, "package": ["Full House"]}},
            "mtv_rocks": {"name": "MTV Rocks",
                          "sd": {"key": 315, "package": ["Full House"]}},
            "vh1": {"name": "VH1",
                    "sd": {"key": 316, "package": ["Fun", "Full House"]}},
            "mtv_omg": {"name": "MTV OMG",
                        "sd": {"key": 318, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "4music": {"name": "4 Music",
                       "sd": {"key": 337, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "31786"}}},
            "the_box": {"name": "The Box",
                        "sd": {"key": 335, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "21492"}}},
            "kiss": {"name": "Kiss",
                     "sd": {"key": 338, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "25151"}}},
            "box_hits": {"name": "Box Hits",
                         "sd": {"key": 336, "package": ["Fun", "Full House"]}},
            "box_upfront": {"name": "Box Upfront",
                            "sd": {"key": 330, "package": ["Fun", "Full House"]}},
            "magic": {"name": "Magic",
                      "sd": {"key": 340, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "25607"}}},
            "kerrang_tv": {"name": "Kerrang! TV",
                           "sd": {"key": 342, "package": ["Fun", "Full House"]}},
            "clubland": {"name": "Clubland",
                         "sd": {"key": 345, "package": ["Mix", "Fun", "Full House"]}},
            "bbc_news": {"name": "BBC News",
                         "sd": {"key": 601, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "19037"}},
                         "hd": {"key": 604, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "sky_news": {"name": "Sky News",
                         "sd": {"key": 602, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "16234"}},
                         "hd": {"key": 603, "package": ["Full House"]}},
            "bbc_parliament": {"name": "BBC Parliament",
                               "sd": {"key": 605, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "20685"}}},
            "cnn": {"name": "CNN",
                    "sd": {"key": 607, "package": ["Player", "Mix", "Fun", "Full House"], "dataSources": {0: "68053"}}},
            "bloomberg": {"name": "Bloomberg",
                          "hd": {"key": 609, "package": ["Mix", "Fun", "Full House"]}},
            "cnbc": {"name": "CNBC",
                     "sd": {"key": 613, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "euronews": {"name": "Euronews",
                         "sd": {"key": 620, "package": ["Mix", "Fun", "Full House"]}},
            "ndtv24x7": {"name": "NDTV 24x7",
                          "sd": {"key": 621, "package": ["Mix", "Fun", "Full House"], "dataSources": {0: "74025"}}},
            "bbc_radio_1": {"name": "BBC Radio 1",
                            "sd": {"key": 901, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_1_xtra": {"name": "BBC Radio 1 Xtra",
                                 "sd": {"key": 907, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_2": {"name": "BBC Radio 2",
                            "sd": {"key": 902, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_3": {"name": "BBC Radio 3",
                            "sd": {"key": 903, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_4_fm": {"name": "BBC Radio 4 FM",
                               "sd": {"key": 904, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_4_extra": {"name": "BBC Radio 4 Extra",
                                  "sd": {"key": 910, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_4_long_wave": {"name": "BBC Radio 4 Long Wave",
                                      "sd": {"key": 911, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_5_live": {"name": "BBC Radio 5 Live",
                                 "sd": {"key": 905, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_5_live_sports_extra": {"name": "BBC Radio 5 Live Sports Extra",
                                              "sd": {"key": 908, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_radio_6_music": {"name": "BBC Radio 6 Music",
                                  "sd": {"key": 909, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "bbc_world_service": {"name": "BBC World Service",
                                  "sd": {"key": 906, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "absolute_radio": {"name": "Absolute Radio",
                               "sd": {"key": 915, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "smooth_radio": {"name": "Smooth Radio",
                             "sd": {"key": 916, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "heart_fm": {"name": "Heart FM",
                         "sd": {"key": 918, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "lbc": {"name": "LBC",
                    "sd": {"key": 919, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "classic_fm": {"name": "Classic FM",
                           "sd": {"key": 922, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "gold_radio": {"name": "Gold Radio",
                           "sd": {"key": 923, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "planet_rock": {"name": "Planet Rock",
                            "sd": {"key": 924, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "magic_radio": {"name": "Magic Radio",
                            "sd": {"key": 928, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "absolute80s": {"name": "Absolute 80s",
                            "sd": {"key": 951, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "absolute_classic_rock": {"name": "Absolute Classic Rock",
                                      "sd": {"key": 952, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "capital_fm": {"name": "Capital FM",
                           "sd": {"key": 958, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "capital_xtra": {"name": "Capital Xtra",
                             "sd": {"key": 959, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "radio_x": {"name": "Radio X",
                        "sd": {"key": 960, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "kiss_fm": {"name": "Kiss FM",
                        "sd": {"key": 963, "package": ["Player", "Mix", "Fun", "Full House"]}},
            "talksport": {"name": "talkSPORT",
                          "sd": {"key": 927, "package": ["Player", "Mix", "Fun", "Full House"]}}
            }
