channels = {"BBC ONE": {"sd": {"key": 101, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": {"key": 108, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "BBC TWO": {"sd": {"key": 102, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": {"key": 162, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "ITV": {"sd": {"key": 103, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": {"key": 113, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Channel 4": {"sd": {"key": 104, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": {"key": 141, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Channel 4 +1": {"sd": {"key": 142, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "Channel 5": {"sd": {"key": 105, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": {"key": 150, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Channel 5 +1": {"sd": {"key": 155, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "My5": {"sd": {"key": 152, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": False},
            "BBC FOUR": {"sd": {"key": 107, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": {"key": 163, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Sky1": {"sd": {"key": 109, "package": ["Mix", "Full House", "VIP"]},
                     "hd": {"key": 110, "package": ["Full House", "VIP"]}},
            "Sky2": {"sd": {"key": 121, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "Sky Living": {"sd": {"key": 112, "package": ["Mix", "Full House", "VIP"]},
                           "hd": {"key": 111, "package": ["Full House", "VIP"]}},
            "Sky Living +1": {"sd": {"key": 140, "package": ["Mix", "Full House", "VIP"]},
                              "hd": False},
            "ITV +1": {"sd": {"key": 114, "package": ["Player", "Mix", "Full House", "VIP"]},
                       "hd": False},
            "ITV2": {"sd": {"key": 115, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": {"key": 176, "package": ["Full House", "VIP"]}},
            "ITV2 +1": {"sd": {"key": 116, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "ITV3": {"sd": {"key": 117, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": {"key": 177, "package": ["Full House", "VIP"]}},
            "ITV3 +1": {"sd": {"key": 174, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "ITV4": {"sd": {"key": 118, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": {"key": 178, "package": ["Full House", "VIP"]}},
            "ITV4 +1": {"sd": {"key": 175, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "ITVBe": {"sd": {"key": 119, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": {"key": 179, "package": ["Full House", "VIP"]}},
            "ITVBe +1": {"sd": {"key": 120, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": False},
            "Sky Arts": {"sd": {"key": 122, "package": ["Mix", "Full House", "VIP"]},
                         "hd": {"key": 206, "package": ["Full House", "VIP"]}},
            "Pick": {"sd": {"key": 123, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": False},
            "W": {"sd": {"key": 125, "package": ["Mix", "Full House", "VIP"]},
                  "hd": {"key": 191, "package": ["Full House", "VIP"]}},
            "W +1": {"sd": {"key": 131, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "Gold": {"sd": {"key": 124, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "Gold +1": {"sd": {"key": 190, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "Dave": {"sd": {"key": 127, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": {"key": 194, "package": ["Full House", "VIP"]}},
            "Dave ja vu": {"sd": {"key": 211, "package": ["Player", "Mix", "Full House", "VIP"]},
                           "hd": False},
            "Alibi": {"sd": {"key": 126, "package": ["Mix", "Full House", "VIP"]},
                      "hd": {"key": 200, "package": ["Full House", "VIP"]}},
            "Alibi +1": {"sd": {"key": 130, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "Comedy Central": {"sd": {"key": 132, "package": ["Mix", "Full House", "VIP"]},
                               "hd": {"key": 181, "package": ["Full House", "VIP"]}},
            "Comedy Central +1": {"sd": {"key": 133, "package": ["Mix", "Full House", "VIP"]},
                                  "hd": False},
            "Comedy Central Extra": {"sd": {"key": 182, "package": ["Full House", "VIP"]},
                                     "hd": False},
            "MTV": {"sd": {"key": 134, "package": ["Mix", "Full House", "VIP"]},
                    "hd": {"key": 183, "package": ["Full House", "VIP"]}},
            "syfy": {"sd": {"key": 135, "package": ["Mix", "Full House", "VIP"]},
                     "hd": {"key": 165, "package": ["Full House", "VIP"]}},
            "syfy +1": {"sd": {"key": 136, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "Universal Channel": {"sd": {"key": 137, "package": ["Mix", "Full House", "VIP"]},
                                  "hd": {"key": 164, "package": ["Full House", "VIP"]}},
            "Universal Channel +1": {"sd": {"key": 138, "package": ["Mix", "Full House", "VIP"]},
                                     "hd": False},
            "Challenge": {"sd": {"key": 139, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": False},
            "Challenge +1": {"sd": {"key": 180, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "E4": {"sd": {"key": 106, "package": ["Player", "Mix", "Full House", "VIP"]},
                   "hd": {"key": 145, "package": ["Full House", "VIP"]}},
            "E4 +1": {"sd": {"key": 146, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "More4": {"sd": {"key": 147, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": {"key": 195, "package": ["Full House", "VIP"]}},
            "More4 +1": {"sd": {"key": 196, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "CBS Reality": {"sd": {"key": 148, "package": ["Mix", "Full House", "VIP"]},
                            "hd": False},
            "CBS Reality +1": {"sd": {"key": 201, "package": ["Mix", "Full House", "VIP"]},
                               "hd": False},
            "Horror Channel": {"sd": {"key": 149, "package": ["Mix", "Full House", "VIP"]},
                               "hd": False},
            "Horror Channel +1": {"sd": {"key": 202, "package": ["Mix", "Full House", "VIP"]},
                                  "hd": False},
            "5*": {"sd": {"key": 151, "package": ["Player", "Mix", "Full House", "VIP"]},
                   "hd": False},
            "5* +1": {"sd": {"key": 185, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "5 USA": {"sd": {"key": 153, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "5 USA +1": {"sd": {"key": 186, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": False},
            "5 Spike": {"sd": {"key": 154, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "E! Entertainment": {"sd": {"key": 156, "package": ["Mix", "Full House", "VIP"]},
                                 "hd": False},
            "FOX": {"sd": {"key": 157, "package": ["Mix", "Full House", "VIP"]},
                    "hd": {"key": 199, "package": ["Full House", "VIP"]}},
            "FOX +1": {"sd": {"key": 158, "package": ["Mix", "Full House", "VIP"]},
                       "hd": False},
            "Made in Leeds": {"sd": {"key": 159, "package": ["Player", "Mix", "Full House", "VIP"]},
                              "hd": False},
            "Real Lives": {"sd": {"key": 160, "package": ["Mix", "Full House", "VIP"]},
                           "hd": False},
            "Real Lives +1": {"sd": {"key": 207, "package": ["Mix", "Full House", "VIP"]},
                              "hd": False},
            "BBC ALBA": {"sd": {"key": 161, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": False},
            "S4C": {"sd": {"key": 166, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": False},
            "TLC": {"sd": {"key": 167, "package": ["Mix", "Full House", "VIP"]},
                    "hd": {"key": 168, "package": ["Full House", "VIP"]}},
            "TLC +1": {"sd": {"key": 169, "package": ["Mix", "Full House", "VIP"]},
                       "hd": False},
            "DMAX": {"sd": {"key": 213, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "DMAX +1": {"sd": {"key": 214, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "Quest": {"sd": {"key": 172, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "Quest +1": {"sd": {"key": 173, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": False},
            "BET": {"sd": {"key": 184, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": False},
            "True Entertainment": {"sd": {"key": 189, "package": ["Mix", "Full House", "VIP"]},
                                   "hd": False},
            "Drama": {"sd": {"key": 128, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "CBS Action": {"sd": {"key": 192, "package": ["Mix", "Full House", "VIP"]},
                           "hd": False},
            "Sony TV": {"sd": {"key": 193, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "4Seven": {"sd": {"key": 143, "package": ["Player", "Mix", "Full House", "VIP"]},
                       "hd": {"key": 203, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "CBS Drama": {"sd": {"key": 197, "package": ["Full House", "VIP"]},
                          "hd": False},
            "TruTV": {"sd": {"key": 212, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": False},
            "Sky Cinema Premiere": {"sd": {"key": 431, "package": ["VIP", "movies_sky"]},
                                    "hd": {"key": 401, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Premiere +1": {"sd": {"key": 402, "package": ["VIP", "movies_sky"]},
                                       "hd": False},
            "Sky Cinema Hits": {"sd": {"key": 433, "package": ["VIP", "movies_sky"]},
                                "hd": {"key": 403, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Greats": {"sd": {"key": 434, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 404, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Disney": {"sd": {"key": 435, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 405, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Family": {"sd": {"key": 436, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 406, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Action": {"sd": {"key": 437, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 407, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Comedy": {"sd": {"key": 438, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 408, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Thriller": {"sd": {"key": 439, "package": ["VIP", "movies_sky"]},
                                    "hd": {"key": 409, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Drama": {"sd": {"key": 440, "package": ["VIP", "movies_sky"]},
                                 "hd": {"key": 410, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Sci Fi & Horror": {"sd": {"key": 441, "package": ["VIP", "movies_sky"]},
                                           "hd": {"key": 411, "package": ["VIP", "movies_sky_hd"]}},
            "Sky Cinema Select": {"sd": {"key": 442, "package": ["VIP", "movies_sky"]},
                                  "hd": {"key": 412, "package": ["VIP", "movies_sky_hd"]}},
            "TCM": {"sd": {"key": 415, "package": ["Mix", "Full House", "VIP"]},
                    "hd": {"key": 416, "package": ["Full House", "VIP"]}},
            "TCM +1": {"sd": {"key": 417, "package": ["Mix", "Full House", "VIP"]},
                       "hd": False},
            "Movies 24": {"sd": {"key": 419, "package": ["Mix", "Full House", "VIP"]},
                          "hd": False},
            "Movies 24 +1": {"sd": {"key": 420, "package": ["Mix", "Full House", "VIP"]},
                             "hd": False},
            "True Movies": {"sd": {"key": 424, "package": ["Full House", "VIP"]},
                            "hd": False},
            "Sony Movie Channel": {"sd": {"key": 425, "package": ["Mix", "Full House", "VIP"]},
                                   "hd": False},
            "Film4": {"sd": {"key": 428, "package": ["Player", "Mix", "Full House", "VIP"]},
                      "hd": {"key": 429, "package": ["Mix", "Full House", "VIP"]}},
            "Film4 +1": {"sd": {"key": 430, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "Sky Sports News": {"sd": {"key": 519, "package": ["Mix", "Full House", "VIP"]},
                                "hd": {"key": 509, "package": ["Full House", "VIP"]}},
            "Sky Sports Mix": {"sd": {"key": 520, "package": ["Mix", "Full House", "VIP"]},
                               "hd": {"key": 510, "package": ["Full House", "VIP"]}},
            "Sky Sports Main Event": {"sd": {"key": 511, "package": ["VIP"]},
                                      "hd": {"key": 501, "package": ["VIP"]}},
            "Sky Sports Premier League": {"sd": {"key": 512, "package": ["VIP"]},
                                          "hd": {"key": 502, "package": ["VIP"]}},
            "Sky Sports Football": {"sd": {"key": 513, "package": ["VIP"]},
                                    "hd": {"key": 503, "package": ["VIP"]}},
            "Sky Sports Cricket": {"sd": {"key": 514, "package": ["VIP"]},
                                   "hd": {"key": 504, "package": ["VIP"]}},
            "Sky Sports Golf": {"sd": {"key": 515, "package": ["VIP"]},
                                "hd": {"key": 505, "package": ["VIP"]}},
            "Sky Sports F1": {"sd": {"key": 516, "package": ["VIP"]},
                              "hd": {"key": 506, "package": ["VIP"]}},
            "Sky Sports Action": {"sd": {"key": 517, "package": ["VIP"]},
                                  "hd": {"key": 507, "package": ["VIP"]}},
            "Sky Sports Arena": {"sd": {"key": 518, "package": ["VIP"]},
                                 "hd": {"key": 508, "package": ["VIP"]}},
            "At The Races": {"sd": {"key": 535, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "BT Sport 1": {"sd": {"key": 531, "package": ["Full House", "VIP"]},
                           "hd": {"key": 527, "package": ["Full House", "VIP"]}},
            "BT Sport 2": {"sd": {"key": 532, "package": ["Full House", "VIP"]},
                           "hd": {"key": 528, "package": ["Full House", "VIP"]}},
            "BT Sport 3": {"sd": {"key": 533, "package": ["Full House", "VIP"]},
                           "hd": {"key": 529, "package": ["Full House", "VIP"]}},
            "BT Sport ESPN": {"sd": {"key": 534, "package": ["Full House", "VIP"]},
                              "hd": {"key": 530, "package": ["Full House", "VIP"]}},
            "Eurosport 1": {"sd": {"key": 523, "package": ["Mix", "Full House", "VIP"]},
                            "hd": {"key": 521, "package": ["Full House", "VIP"]}},
            "Eurosport 2": {"sd": {"key": 524, "package": ["Mix", "Full House", "VIP"]},
                            "hd": {"key": 522, "package": ["Full House", "VIP"]}},
            "Motorsport TV": {"sd": {"key": 545, "package": ["Mix", "Full House", "VIP"]},
                              "hd": False},
            "FIA Formula E": {"sd": {"key": 000, "package": ["Full House", "VIP"]},
                              "hd": {"key": 000, "package": ["Full House", "VIP"]}},
            "BIKE": {"sd": {"key": 000, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "COPA90": {"sd": {"key": 000, "package": ["Mix", "Full House", "VIP"]},
                       "hd": False},
            "Yesterday": {"sd": {"key": 245, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": False},
            "Yesterday +1": {"sd": {"key": 246, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "Eden": {"sd": {"key": 247, "package": ["Full House", "VIP"]},
                     "hd": {"key": 249, "package": ["Full House", "VIP"]}},
            "Eden +1": {"sd": {"key": 248, "package": ["Full House", "VIP"]},
                        "hd": False},
            "Discovery Channel": {"sd": {"key": 250, "package": ["Full House", "VIP"]},
                                  "hd": {"key": 251, "package": ["Full House", "VIP"]}},
            "Discovery Channel +1": {"sd": {"key": 252, "package": ["Full House", "VIP"]},
                                     "hd": False},
            "Investigation Discovery": {"sd": {"key": 253, "package": ["Mix", "Full House", "VIP"]},
                                        "hd": False},
            "Investigation Discovery +1": {"sd": {"key": 254, "package": ["Mix", "Full House", "VIP"]},
                                           "hd": False},
            "Animal Planet": {"sd": {"key": 256, "package": ["Full House", "VIP"]},
                              "hd": {"key": 257, "package": ["Full House", "VIP"]}},
            "Animal Planet +1": {"sd": {"key": 258, "package": ["Full House", "VIP"]},
                                 "hd": False},
            "Discovery Science": {"sd": {"key": 259, "package": ["Full House", "VIP"]},
                                  "hd": False},
            "Discovery Science +1": {"sd": {"key": 260, "package": ["Full House", "VIP"]},
                                     "hd": False},
            "Discovery Turbo": {"sd": {"key": 261, "package": ["Full House", "VIP"]},
                                "hd": False},
            "Discovery History": {"sd": {"key": 262, "package": ["Full House", "VIP"]},
                                  "hd": False},
            "Discovery History +1": {"sd": {"key": 263, "package": ["Full House", "VIP"]},
                                     "hd": False},
            "Nat Geo Wild": {"sd": {"key": False, "264": ["Full House", "VIP"]},
                             "hd": {"key": 265, "package": ["Full House", "VIP"]}},
            "National Geographic": {"sd": {"key": 266, "package": ["Full House", "VIP"]},
                                    "hd": {"key": 268, "package": ["Full House", "VIP"]}},
            "National Geographic +1": {"sd": {"key": 267, "package": ["Full House", "VIP"]},
                                       "hd": False},
            "Community Channel": {"sd": {"key": 269, "package": ["Player", "Mix", "Full House", "VIP"]},
                                  "hd": False},
            "History": {"sd": {"key": 270, "package": ["Full House", "VIP"]},
                        "hd": False},
            "History +1": {"sd": {"key": 271, "package": ["Full House", "VIP"]},
                           "hd": False},
            "H2": {"sd": {"key": 273, "package": ["Full House", "VIP"]},
                   "hd": {"key": 274, "package": ["Full House", "VIP"]}},
            "Lifetime": {"sd": {"key": 208, "package": ["Full House", "VIP"]},
                         "hd": {"key": 209, "package": ["Full House", "VIP"]}},
            "Crime and Investigation": {"sd": {"key": 275, "package": ["Full House", "VIP"]},
                                        "hd": False},
            "PBS America": {"sd": {"key": 276, "package": ["Mix", "Full House", "VIP"]},
                            "hd": False},
            "Forces TV": {"sd": {"key": 277, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": False},
            "Good Food": {"sd": {"key": 278, "package": ["Full House", "VIP"]},
                          "hd": {"key": 280, "package": ["Full House", "VIP"]}},
            "Good Food +1": {"sd": {"key": 279, "package": ["Full House", "VIP"]},
                             "hd": False},
            "Food Network": {"sd": {"key": 291, "package": ["Mix", "Full House", "VIP"]},
                             "hd": False},
            "Home": {"sd": {"key": 281, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": False},
            "Home +1": {"sd": {"key": 282, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "Really": {"sd": {"key": 129, "package": ["Player", "Mix", "Full House", "VIP"]},
                       "hd": False},
            "Discovery Home & Health": {"sd": {"key": 284, "package": ["Full House", "VIP"]},
                                        "hd": False},
            "Discovery Home & Health +1": {"sd": {"key": 285, "package": ["Full House", "VIP"]},
                                           "hd": False},
            "Discovery Shed": {"sd": {"key": 286, "package": ["Full House", "VIP"]},
                               "hd": False},
            "Ginx Esports TV": {"sd": {"key": 290, "package": ["Full House", "VIP"]},
                                "hd": False},
            "Travel Channel": {"sd": {"key": 292, "package": ["Mix", "Full House", "VIP"]},
                               "hd": False},
            "CBBC": {"sd": {"key": 701, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": {"key": 710, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Cbeebies": {"sd": {"key": 702, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": {"key": 711, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Cartoon Network": {"sd": {"key": 704, "package": ["Mix", "Full House", "VIP"]},
                                "hd": {"key": 732, "package": ["Full House", "VIP"]}},
            "Cartoon Network +1": {"sd": {"key": 705, "package": ["Mix", "Full House", "VIP"]},
                                   "hd": False},
            "Cartoonito": {"sd": {"key": 706, "package": ["Mix", "Full House", "VIP"]},
                           "hd": False},
            "Disney XD": {"sd": {"key": 707, "package": ["Full House", "VIP"]},
                          "hd": False},
            "Disney XD +1": {"sd": {"key": 708, "package": ["Full House", "VIP"]},
                             "hd": False},
            "Nickelodeon": {"sd": {"key": 712, "package": ["Full House", "VIP"]},
                            "hd": {"key": 714, "package": ["Full House", "VIP"]}},
            "Nickelodeon +1": {"sd": {"key": 713, "package": ["Full House", "VIP"]},
                               "hd": False},
            "Nick Junior": {"sd": {"key": 715, "package": ["Full House", "VIP"]},
                            "hd": False},
            "Nick Junior Too": {"sd": {"key": 716, "package": ["Full House", "VIP"]},
                                "hd": False},
            "Nick Toons": {"sd": {"key": 717, "package": ["Full House", "VIP"]},
                           "hd": False},
            "Disney Channel": {"sd": {"key": 724, "package": ["Full House", "VIP"]},
                               "hd": False},
            "Disney Channel +1": {"sd": {"key": 725, "package": ["Full House", "VIP"]},
                                  "hd": False},
            "Disney Junior": {"sd": {"key": 727, "package": ["Full House", "VIP"]},
                              "hd": False},
            "Boomerang": {"sd": {"key": 730, "package": ["Mix", "Full House", "VIP"]},
                          "hd": False},
            "Boomerang +1": {"sd": {"key": 731, "package": ["Mix", "Full House", "VIP"]},
                             "hd": False},
            "CITV": {"sd": {"key": 734, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": False},
            "Pop": {"sd": {"key": 736, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "Tiny Pop": {"sd": {"key": 737, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "MTV Music": {"sd": {"key": 310, "package": ["Mix", "Full House", "VIP"]},
                          "hd": False},
            "MTV Live HD": {"sd": False,
                            "hd": {"key": 311, "package": ["Full House", "VIP"]}},
            "MTV Hits": {"sd": {"key": 312, "package": ["Full House", "VIP"]},
                         "hd": False},
            "MTV Base": {"sd": {"key": 313, "package": ["Full House", "VIP"]},
                         "hd": False},
            "MTV Dance": {"sd": {"key": 314, "package": ["Full House", "VIP"]},
                          "hd": False},
            "MTV Rocks": {"sd": {"key": 315, "package": ["Full House", "VIP"]},
                          "hd": False},
            "VH1": {"sd": {"key": 316, "package": ["Full House", "VIP"]},
                    "hd": False},
            "Viva": {"sd": {"key": 317, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": False},
            "4 Music": {"sd": {"key": 337, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "The Box": {"sd": {"key": 335, "package": ["Mix", "Full House", "VIP"]},
                        "hd": False},
            "Kiss": {"sd": {"key": 338, "package": ["Mix", "Full House", "VIP"]},
                     "hd": False},
            "Box Hits": {"sd": {"key": 336, "package": ["Full House", "VIP"]},
                           "hd": False},
            "Box Upfront": {"sd": {"key": 220, "package": ["Full House", "VIP"]},
                            "hd": False},
            "Magic": {"sd": {"key": 340, "package": ["Mix", "Full House", "VIP"]},
                      "hd": False},
            "Kerrang! TV": {"sd": {"key": 342, "package": ["Full House", "VIP"]},
                            "hd": False},
            "Vintage TV": {"sd": {"key": 343, "package": ["Mix", "Full House", "VIP"]},
                           "hd": False},
            "Clubland": {"sd": {"key": 345, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "BBC News": {"sd": {"key": 601, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": {"key": 604, "package": ["Player", "Mix", "Full House", "VIP"]}},
            "Sky News": {"sd": {"key": 602, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": {"key": 603, "package": ["Full House", "VIP"]}},
            "BBC Parliament": {"sd": {"key": 605, "package": ["Player", "Mix", "Full House", "VIP"]},
                               "hd": False},
            "CNN": {"sd": {"key": 607, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": False},
            "Bloomberg": {"sd": {"key": 609, "package": ["Mix", "Full House", "VIP"]},
                          "hd": False},
            "CNBC": {"sd": {"key": 613, "package": ["Player", "Mix", "Full House", "VIP"]},
                     "hd": False},
            "Euronews": {"sd": {"key": 620, "package": ["Mix", "Full House", "VIP"]},
                         "hd": False},
            "NDTV 24x7": {"sd": {"key": 621, "package": ["Mix", "Full House", "VIP"]},
                          "hd": False},
            "BBC Radio 1": {"sd": {"key": 901, "package": ["Player", "Mix", "Full House", "VIP"]},
                            "hd": False},
            "BBC Radio 1 Xtra": {"sd": {"key": 907, "package": ["Player", "Mix", "Full House", "VIP"]},
                                 "hd": False},
            "BBC Radio 2": {"sd": {"key": 902, "package": ["Player", "Mix", "Full House", "VIP"]},
                            "hd": False},
            "BBC Radio 3": {"sd": {"key": 903, "package": ["Player", "Mix", "Full House", "VIP"]},
                            "hd": False},
            "BBC Radio 4 FM": {"sd": {"key": 904, "package": ["Player", "Mix", "Full House", "VIP"]},
                               "hd": False},
            "BBC Radio 4 Extra": {"sd": {"key": 910, "package": ["Player", "Mix", "Full House", "VIP"]},
                                  "hd": False},
            "BBC Radio 4 Long Wave": {"sd": {"key": 911, "package": ["Player", "Mix", "Full House", "VIP"]},
                                      "hd": False},
            "BBC Radio 5 Live": {"sd": {"key": 905, "package": ["Player", "Mix", "Full House", "VIP"]},
                                 "hd": False},
            "BBC Radio 5 Live Sports Extra": {"sd": {"key": 908, "package": ["Player", "Mix", "Full House", "VIP"]},
                                              "hd": False},
            "BBC Radio 6 Music": {"sd": {"key": 909, "package": ["Player", "Mix", "Full House", "VIP"]},
                                  "hd": False},
            "BBC World Service": {"sd": {"key": 906, "package": ["Player", "Mix", "Full House", "VIP"]},
                                  "hd": False},
            "Absolute Radio": {"sd": {"key": 915, "package": ["Player", "Mix", "Full House", "VIP"]},
                               "hd": False},
            "Smooth Radio": {"sd": {"key": 916, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "Heart FM": {"sd": {"key": 918, "package": ["Player", "Mix", "Full House", "VIP"]},
                         "hd": False},
            "LBC": {"sd": {"key": 919, "package": ["Player", "Mix", "Full House", "VIP"]},
                    "hd": False},
            "Classic FM": {"sd": {"key": 922, "package": ["Player", "Mix", "Full House", "VIP"]},
                           "hd": False},
            "Gold Radio": {"sd": {"key": 923, "package": ["Player", "Mix", "Full House", "VIP"]},
                           "hd": False},
            "Planet Rock": {"sd": {"key": 924, "package": ["Player", "Mix", "Full House", "VIP"]},
                            "hd": False},
            "Magic Radio": {"sd": {"key": 928, "package": ["Player", "Mix", "Full House", "VIP"]},
                            "hd": False},
            "Absolute 80s": {"sd": {"key": 951, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "Absolute Classic Rock": {"sd": {"key": 952, "package": ["Player", "Mix", "Full House", "VIP"]},
                                      "hd": False},
            "Capital FM": {"sd": {"key": 958, "package": ["Player", "Mix", "Full House", "VIP"]},
                           "hd": False},
            "Capital Xtra": {"sd": {"key": 959, "package": ["Player", "Mix", "Full House", "VIP"]},
                             "hd": False},
            "Radio X": {"sd": {"key": 960, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "Kiss FM": {"sd": {"key": 963, "package": ["Player", "Mix", "Full House", "VIP"]},
                        "hd": False},
            "talkSPORT": {"sd": {"key": 927, "package": ["Player", "Mix", "Full House", "VIP"]},
                          "hd": False}
            }